version: '3'

vars:
  INVENTORY: inventory/wsl2.yml
  PLAYBOOK: playbooks/site.yml

tasks:
  # Explicit name for clarity
  provision:
    desc: Provision everything with Ansible on localhost
    cmds:
      - sudo ansible-playbook -i {{.INVENTORY}} {{.PLAYBOOK}}
