version: '3'

tasks:
  # Provision WSL2 stack
  provision:wsl2:
    desc: Provision WSL2 environment on localhost
    cmds:
      - sudo ansible-playbook playbooks/wsl2.yml

  # Provision Ubuntu Desktop stack
  provision:ubuntu-desktop:
    desc: Provision Ubuntu Desktop environment on localhost
    cmds:
      - sudo ansible-playbook playbooks/ubuntu-desktop.yml

  # Provision Ubuntu Server stack
  provision:ubuntu-server:
    desc: Provision Ubuntu Server environment on localhost
    cmds:
      - sudo ansible-playbook playbooks/ubuntu-server.yml

  # Backward-compatible alias (defaults to WSL2)
  provision:
    desc: Provision everything (defaults to WSL2) on localhost
    cmds:
      - sudo ansible-playbook playbooks/wsl2.yml

  # Lint the project
  lint:
    desc: Run ansible-lint using docker and check playbook syntax
    cmds:
      - ansible-playbook --syntax-check playbooks/wsl2.yml
      - ansible-playbook --syntax-check playbooks/ubuntu-desktop.yml
      - ansible-playbook --syntax-check playbooks/ubuntu-server.yml
      - docker run --rm -v {{.USER_WORKING_DIR}}:/work -w /work pipelinecomponents/ansible-lint:latest ansible-lint
